[project]
name = "python"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
  "pip>=25.2",
  "silero-vad>=6.2.0",
  "soundfile>=0.13.1",
  #TODO: update torch 
  "torch==2.8.0",
  "torchaudio==2.8.0",
]

[dependency-groups]
dev = ["pyright>=1.1.406", "ruff>=0.13.3"]

[tool.uv.sources]
torch = [{ index = "pytorch-cpu" }]
torchaudio = [{ index = "pytorch-cpu" }]
torchvision = [{ index = "pytorch-cpu" }]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
